// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrkpvmcqyjrfaccbdkgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpya3B2bWNxeWpyZmFjY2Jka2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTc3MDcsImV4cCI6MjA3MzU3MzcwN30.sem5u0IGzZZ5EJoUZPZwqMoWO7-cxbJZmiOyrKlB8cA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});